baseURL = 'https://jpcorps.github.io/'
title = 'My New Blog'
theme = []

defaultContentLanguage = 'ko'

[languages]
  [languages.ko]
    languageCode = 'ko-kr'
    languageName = 'Korean'
    weight = 1