baseURL = "https://jpcorps.com/"
title = "대충 살아가는 게임개발자"
theme = "hugo-theme-stack"
defaultContentLanguage = "ko"
hasCJKLanguage = true

[outputs]
home = ["html", "rss", "json"]

[params]
mainSections = ["posts"]

[params.pwa]
enabled = false

[params.sidebar]
subtitle = "이글루스와 티스토리를 거쳐 방황하다가 여기까지 대충 흘러왔습니다"
avatar = "profile.png"

[params.comments]
enabled = true
provider = "giscus"

[params.comments.giscus]
repo = "jpcorps/jpcorps.github.io"
repoId = "R_kgDOSSJrIA"
category = "Announcements"
categoryId = "DIC_kwDOSSJrIM4C8P_5"
mapping = "pathname"
strict = "0"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
lang = "ko"
lightTheme = "light"
darkTheme = "transparent_dark"

[params.article]
[params.article.editLink]
url = "https://github.com/jpcorps/jpcorps.github.io/edit/main/content"
title = "이 페이지 수정하기"

[[menu.main]]
identifier = "categories"
name = "카테고리"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "egloos-backup"
name = " └ 이글루스 백업"
url = "/categories/이글루스-백업/"
weight = 11

[[menu.main]]
identifier = "search"
name = "검색"
url = "/search/"
weight = 20

[languages]
[languages.ko]
languageCode = "ko-kr"
languageName = "Korean"
weight = 1
