backend:
  name: github
  repo: jpcorps/jpcorps.github.io # 본인의 레포지토리 경로
  branch: main

media_folder: "static/images" # 이미지가 저장될 경로
public_folder: "/images"

collections:
  - name: "posts"
    label: "포스트"
    folder: "content/posts"
    create: true
    delete: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }