backend:
  name: git-gateway
  branch: main
  site_domain: polite-platypus-6dafcc.netlify.app

media_folder: "static/images" # 이미지가 저장될 경로
public_folder: "/images"

collections:
  - name: "posts"
    label: "포스트"
    folder: "content/posts"
    create: true
    delete: true
    view_filters:
      - { label: "임시 저장글", field: "draft", pattern: true }
    view_groups:
      - { label: "카테고리별", field: "categories" }
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "카테고리", name: "categories", widget: "select", options: ["일반", "튜터리얼", "공부자료", "백업"], default: "일반" }
      - { label: "Body", name: "body", widget: "markdown" }